# Generated by Django 5.0.6 on 2026-02-05 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Present", "Present"), ("Absent", "Absent")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "db_table": "attendance",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["employee", "date"],
                        name="attendance_employe_c9bb2b_idx",
                    ),
                    models.Index(fields=["date"], name="attendance_date_d460ba_idx"),
                ],
                "unique_together": {("employee", "date")},
            },
        ),
    ]
