# Generated by Django 5.0.6 on 2026-02-05 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("full_name", models.CharField(max_length=200)),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("department", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "employees",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["employee_id"], name="employees_employe_0b5eb0_idx"
                    ),
                    models.Index(fields=["email"], name="employees_email_f66e96_idx"),
                ],
            },
        ),
    ]
